# NumPy Day 1 — Code Lab

**Level:** Beginner  
**Goal:** Learn NumPy arrays, properties, indexing, slicing, arithmetic, comparisons, and basic ML-style data handling.

### Topics
1. Import NumPy
2. Create 1D and 2D arrays
3. Array properties
4. Indexing
5. Slicing
6. Array arithmetic
7. Comparison operations
8. Mini ML dataset
9. Challenge


## Part 1 — Import NumPy

In [2]:
# Task 1: Import NumPy and print its version

import numpy as np

print(np.__version__)


1.26.4


In [2]:
# Task 2: Print this message

# Write your code here

arr = np.array([10,20,30,40,50])
print(arr)


[10 20 30 40 50]


## Part 2 — Creating NumPy Arrays

In [3]:
# Task 3: Create a 1D NumPy array
# Values: 10, 20, 30, 40, 50

# Write your code here
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [34]:
arr= np.array([0,1,2,3,4])
print(arr/5)

[0.  0.2 0.4 0.6 0.8]


In [4]:
# Task 4: Create this 2D NumPy array
# [[1, 2, 3],
#  [4, 5, 6]]

# Write your code here
arr_1 = np.array([[1,2,3],[4,5,6]])
print(arr_1)

[[1 2 3]
 [4 5 6]]


In [5]:
# Task 5: Create a NumPy array containing even numbers from 2 to 10

# Write your code here
arr =  np.array([2,4,6,8,10])
print(arr)

[ 2  4  6  8 10]


## Part 3 — Array Properties

In [8]:
# Task 6

arr = np.array([10, 20, 30, 40, 50])

# Find:
# 1. Number of dimensions
# 2. Number of elements
# 3. Data type

# Write your code here

print("dimmension :",arr.ndim)
print("element :",arr.size)

print("data type :",arr.dtype)


dimmension : 1
element : 5
data type : int32


In [3]:
# Task 7

data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Find:
# 1. ndim
# 2. shape
# 3. size
# 4. dtype

# Write your code here
print("Dimension :",data.ndim)
print("shape : " ,data.shape)
print("size : ",data.size)
print("data type :",data.dtype)


Dimension : 2
shape :  (2, 3)
size :  6
data type : int32


## Part 4 — Indexing

In [19]:
# Task 8

arr = np.array([10, 20, 30, 40, 50])

# Print:
# 1. First element
# 2. Third element
# 3. Last element

# Write your code here

print(arr[0])
print(arr[2])
print(arr[4])


10
30
50


In [18]:
# Task 9

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Print:
# 1. 10
# 2. 50
# 3. 90
# 4. 30

# Write your code here
print(data[0,0])
print(data[1,1])
print(data[0,2])

10
50
30


## Part 5 — Slicing

In [ ]:
# Task 10

arr = np.array([[10, 20, 30, 40, 50],[0,0,0,0,0]])

# Print [20 30 40]

# Write your code here
print(arr[0,1:0,4])


[20 30 40]


In [ ]:
# Task 11

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Print:
# 1. First row
print(data[0,1:0,2])# syntax : data:[ start:end ]
# 2. Second row
print(data[1 ,:])
# 3. First column
print(data[ : ,0])
# 4. Second column
print(data[: ,1])

# Write your code here


[20 30]
[40 50 60]
[10 40 70]
[20 50 80]


## Part 6 — Array Arithmetic

In [35]:
# Task 12

arr = np.array([10, 20, 30, 40, 50])

# Perform:
# 1. Add 5
print(arr + 5)
# 2. Subtract 5
# 3. Multiply by 2
# 4. Divide by 2

# Write your code here
print(arr.sum())


[15 25 35 45 55]
150


In [31]:
# Task 13

marks = np.array([70, 80, 65, 90, 75])

# Add 5 bonus marks to every student

# Write your code here
print(marks + 5)

[75 85 70 95 80]


## Part 7 — Comparison Operations

In [4]:
# Task 14

marks = np.array([45, 67, 89, 32, 76, 91])

# Find which marks are:
# 1. Greater than 50
# 2. Less than 50
# 3. Equal to 76

# Write your code here

greater_than_50 = marks > 50
print(greater_than_50)
print(marks < 50)
print(marks == 76)


[False  True  True False  True  True]
[ True False False  True False False]
[False False False False  True False]


## Part 8 — Mini ML Dataset

Imagine this is a small student dataset:

| Age | Marks |
|---:|---:|
| 20 | 80 |
| 21 | 75 |
| 22 | 90 |
| 23 | 65 |
| 24 | 85 |

**Rows = students (samples), columns = features.**

In [5]:
students = np.array([
    [20, 80],
    [21, 75],
    [22, 90],
    [23, 65],
    [24, 85]
])

students


array([[20, 80],
       [21, 75],
       [22, 90],
       [23, 65],
       [24, 85]])

In [6]:
# Task 15: Find the shape of the dataset

# Write your code here
print(students.shape)

(5, 2)


In [8]:
# Task 16: Print the first student's complete data

# Write your code here
print(students[0])

[20 80]


In [9]:
# Task 17: Print the marks of the first student

# Write your code here
print(students[0,1])

80


In [10]:
# Task 18: Print all marks

# Hint: students[:, 1]

# Write your code here
print(students[:,1])

[80 75 90 65 85]


In [11]:
# Task 19: Print all ages

# Hint: students[:, 0]

# Write your code here
print(students[:,0])

[20 21 22 23 24]


In [12]:
# Task 20: Add 5 marks to every student's marks

# Write your code here
print(students[:,1]+5)

[85 80 95 70 90]


## 🔥 Final Challenge

Use the dataset below and solve all tasks **without looking at previous examples**.

```python
students = np.array([
    [20, 80],
    [21, 75],
    [22, 90],
    [23, 65],
    [24, 85]
])
```

### Tasks
1. Find the number of students.
2. Find the number of features.
3. Extract the marks.
4. Extract the ages.
5. Find students with marks greater than 80.
6. Add 10 marks to every student's marks.
7. Print the second student's complete data.


In [28]:
# Final Challenge

students = np.array([
    [20, 80],
    [21, 75],
    [22, 90],
    [23, 65],
    [24, 85]
])

# Solve the 7 tasks here.


print("Find the number of students :",students.shape[0])
print("Find the number of features :",students.shape[1])
print("Extract the marks:",students[:,1])
print("Extract the ages:",students[:,0])
print("Add 10 marks to every student's marks:",students[:,1]+10)
print("Print the second student's complete data :",students[1 : 2])



Find the number of students : 5
Find the number of features : 2
Extract the marks: [80 75 90 65 85]
Extract the ages: [20 21 22 23 24]
Add 10 marks to every student's marks: [ 90  85 100  75  95]
Print the second student's complete data : [[21 75]]
